### ISSUE TITLE
[Enhancement] Add Merkle Sum Tree functionality

### ISSUE THREAD

**Issue by h5law** [pokt-network/smt#10]
## Objective

Merkle Sum Trees in addition to storing the hashes of nodes, also store a sum. This sum is used in conjuction with the node's hash to produce the hash of its parent nodes. A Merkle Sum Tree allows for the computation of the sum of the entire tree.

Adding the functionality of a merkle sum tree to this SMT library will increase the number of areas in which it can be used and the number of purposes for which it can be used.

The implementation of the SMST (Sparse Merkle Sum Tree) should be in accordance with the following documents:
- [Plasma Core Documentation](https://plasma-core.readthedocs.io/en/latest/specs/sum-tree.html)
- [Relay Mining Paper](https://arxiv.org/abs/2305.10672)

## Origin Document

This [pokt-network PR](https://github.com/pokt-network/pocket/issues/776)

## Goals

- Implement a Sparse Merkle Sum Tree
- Add unit tests, fuzz tests and benchmarks
- Add documentation explaining the SMST and how it works

## Deliverable

- [ ] Implement the Sparse Merkle Sum Tree
- [ ] Enable the computation of the tree's sum
- [ ] Enable feature parity with the existing SMT
- [ ] Add unit testing for the SMST
- [ ] Add fuzz tests for the SMST
- [ ] Add benchmarks for the SMST
- [ ] Integrate tests/fuzzes with existing CI workflows

## Non-goals / Non-deliverables

- Change any existing logic related to the SMT functionality

## General issue deliverables

- [ ] Update any relevant README(s)
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `go test ...`
- [ ] **New tests or benchmarks**: `go test ...`
- [ ] **All tests**: `go test -v`

---

**Creator**: @h5law 
**Co-Owners**: @h5law @Olshansk

**Comment by Olshansk** [comment]
Documenting one added request/requirement we discussed offline.

We should make sure there's support for leaves to have different weights (i.e. not just `1`) such that the sum is not just a "leaf count."
